# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shopsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='店铺名称')),
                ('cover', models.ImageField(default='static/images/stores/default/default.jpg', upload_to='covers/')),
                ('intro', models.CharField(max_length=255, verbose_name='店铺介绍')),
                ('status', models.IntegerField(default=0, verbose_name='店铺状态')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='店铺添加时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopsite.NormalUser', verbose_name='店铺店长')),
            ],
        ),
    ]
