# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 06:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recv_name', models.CharField(max_length=255, verbose_name='收货人')),
                ('recv_phone', models.IntegerField(verbose_name='收货人联系方式')),
                ('native', models.CharField(max_length=50, verbose_name='国家')),
                ('provice', models.CharField(max_length=50, verbose_name='省份')),
                ('city', models.CharField(max_length=50, verbose_name='市区')),
                ('country', models.CharField(max_length=50, verbose_name='县区')),
                ('street', models.CharField(max_length=255, verbose_name='街道')),
                ('desc', models.CharField(max_length=255, verbose_name='详细描述')),
                ('status', models.BooleanField(default=False, verbose_name='是否默认地址')),
            ],
        ),
        migrations.CreateModel(
            name='NormalUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=255, unique=True, verbose_name='用户昵称')),
                ('age', models.IntegerField(default=0, verbose_name='用户年龄')),
                ('gender', models.CharField(blank=True, max_length=5, null=True, verbose_name='用户性别')),
                ('header', models.ImageField(default='static/images/headers/default/default.jpg', upload_to='static/images/headers', verbose_name='用户头像')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='用户联系方式')),
                ('email', models.CharField(blank=True, max_length=50, verbose_name='用户邮箱')),
                ('birthday', models.DateTimeField(blank=True, null=True, verbose_name='出生日期')),
                ('status', models.CharField(default=1, max_length=10, verbose_name='用户状态')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShopCart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0, verbose_name='购买数量')),
                ('subtotal', models.FloatField(default=0, verbose_name='小计价格')),
                ('add_time', models.DateTimeField(blank=True, null=True, verbose_name='添加时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shopsite.NormalUser')),
            ],
            options={
                'ordering': ['-add_time'],
            },
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopsite.NormalUser'),
        ),
    ]
