# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 02:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=255, unique=True, verbose_name='用户昵称')),
                ('age', models.IntegerField(default=0, verbose_name='用户年龄')),
                ('gender', models.BooleanField(verbose_name='用户性别')),
                ('header', models.ImageField(default='static/images/headers/default.jpg', upload_to='static/images/headers', verbose_name='用户头像')),
                ('phone', models.CharField(max_length=30, verbose_name='用户联系方式')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
