# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaluser',
            name='gender',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='用户性别'),
        ),
    ]
