# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 01:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopsite', '0002_auto_20181019_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recv_name', models.CharField(max_length=255, verbose_name='收货人')),
                ('recv_phone', models.IntegerField(max_length=50, verbose_name='收货人联系方式')),
                ('native', models.CharField(max_length=50, verbose_name='国家')),
                ('provice', models.CharField(max_length=50, verbose_name='省份')),
                ('city', models.CharField(max_length=50, verbose_name='市区')),
                ('country', models.CharField(max_length=50, verbose_name='县区')),
                ('street', models.CharField(max_length=255, verbose_name='街道')),
                ('desc', models.CharField(max_length=255, verbose_name='详细描述')),
                ('status', models.BooleanField(default=False, verbose_name='是否默认地址')),
            ],
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='header',
            field=models.ImageField(default='/static/images/headers/default.jpg', upload_to='static/images/headers', verbose_name='用户头像'),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopsite.NormalUser'),
        ),
    ]
