# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopsite', '0003_auto_20181022_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='recv_phone',
            field=models.IntegerField(verbose_name='收货人联系方式'),
        ),
    ]
