# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopsite', '0004_auto_20181022_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='normaluser',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True, verbose_name='出生日期'),
        ),
    ]
