# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopsite', '0005_normaluser_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='normaluser',
            name='email',
            field=models.CharField(blank=True, max_length=50, verbose_name='用户邮箱'),
        ),
    ]
